### ISSUE TITLE
Cannot start with adf-autoscan option

### ISSUE THREAD

**Issue by rgallo** [manuc66/node-hp-scan-to#1140]
**Describe the bug**
Device: HP Officejet 4650
Command line or Docker :
```
  hp-scan-to:
    image: docker.io/manuc66/node-hp-scan-to:latest
    restart: no
    environment:
      - IP=192.168.20.52
      - TZ=America/New_York
      - PATTERN="scan"_dd-mm-yyyy_hh-MM-ss
      - PGID=100
      - PUID=1026
      - LABEL=ether
      - MAIN_COMMAND=adf-autoscan --pdf
    volumes:
      - /volume1/docker/paperless/consume:/scan
```

Describe what is happening

When trying to start the container with `MAIN_COMMAND=adf-autoscan --pdf` in the environment, I get a "too many arguments for 'listen'" error, and the container shuts down.  I've tried also quoting the command `MAIN_COMMAND="adf-autoscan --pdf"` and have the same result.  The container starts up fine without this environment setting\.

Please attach the output with debug (-D switch, see documentation)
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/10-adduser

User uid:    1026
User gid:    100
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:/app/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
Current commit ID: 1a776a6249a0b4df3f97bfc233897e2a78cfd40b
error: too many arguments for 'listen'. Expected 0 arguments but got 1.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by manuc66** [comment]
Hi @rgallo 

A documentation bug has recently been introduced in the last documentation update

The main command should not take additional switches, here the updated compose file:

```yaml
  hp-scan-to:
    image: docker.io/manuc66/node-hp-scan-to:latest
    restart: no
    environment:
      - IP=192.168.20.52
      - TZ=America/New_York
      - PATTERN="scan"_dd-mm-yyyy_hh-MM-ss
      - PGID=100
      - PUID=1026
      - LABEL=ether
      - MAIN_COMMAND=adf-autoscan
      - CMDLINE=--pdf
    volumes:
      - /volume1/docker/paperless/consume:/scan
```
